name: ably_cryptocurrency
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ably_flutter_plugin: ^1.0.0+dev.2
  intl: ^0.16.1
  get_it: ^5.0.1
  syncfusion_flutter_charts: ^18.3.52
  tweet_ui: ^2.4.1
  twitter_api: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
